
from .client import MCPTestClient, make_client
from .types import (
    Content,
    Icon,
    JSONRPCErrors,
    MCPAuthRequired,
    MCPCancelledError,
    MCPClientError,
    MCPError,
    MCPForbiddenError,
    MCPServerCrash,
    MCPTimeoutError,
    Prompt,
    Resource,
    ResourceContent,
    SPEC_VERSIONS,
    Task,
    ToolAnnotations,
    ToolList,
    ToolResult,
    ToolSchema,
)
from .assertions import (
    assert_policy_allows,
    assert_policy_blocks,
    assert_tool_content_count,
    assert_tool_error,
    assert_tool_error_code,
    assert_tool_ok,
    assert_tool_text_contains,
    assert_tool_text_equals,
    assert_task_cancelled,
    assert_task_completes_within,
    assert_task_failed,
)
from .auth import (
    AuthConfig,
    build_auth_headers,
    build_m2m_token_request,
    generate_pkce_pair,
    parse_www_authenticate,
    validate_asm_document,
    validate_prm_document,
)
from .schema_validator import (
    ContractTestResult,
    SchemaValidationError,
    generate_valid_inputs,
    validate_schemas,
    validate_tool_schema,
)
from .coverage import CoverageReport, CoverageTracker, PrimitiveCoverage
from .runner import discover_command, discover_timeout, run_tests
from .fixtures import fixture, make_sandboxed_client, seed_fixture_data

__version__ = "0.2.0"

__all__ = [
    "MCPTestClient",
    "make_client",
    "Content",
    "Icon",
    "MCPError",
    "ToolResult",
    "ToolSchema",
    "ToolAnnotations",
    "ToolList",
    "Resource",
    "ResourceContent",
    "Prompt",
    "Task",
    "JSONRPCErrors",
    "SPEC_VERSIONS",
    "MCPClientError",
    "MCPServerCrash",
    "MCPTimeoutError",
    "MCPCancelledError",
    "MCPAuthRequired",
    "MCPForbiddenError",
    "assert_tool_ok",
    "assert_tool_error",
    "assert_tool_error_code",
    "assert_tool_text_contains",
    "assert_tool_text_equals",
    "assert_tool_content_count",
    "assert_policy_allows",
    "assert_policy_blocks",
    "assert_task_completes_within",
    "assert_task_cancelled",
    "assert_task_failed",
    "AuthConfig",
    "build_auth_headers",
    "build_m2m_token_request",
    "generate_pkce_pair",
    "parse_www_authenticate",
    "validate_asm_document",
    "validate_prm_document",
    "SchemaValidationError",
    "ContractTestResult",
    "validate_tool_schema",
    "validate_schemas",
    "generate_valid_inputs",
    "CoverageTracker",
    "CoverageReport",
    "PrimitiveCoverage",
    "discover_command",
    "discover_timeout",
    "run_tests",
    "fixture",
    "make_sandboxed_client",
    "seed_fixture_data",
]
