"""Command-line entry point for pytest-mcp-plugin.

Provides:
  - `mcp-test init`     scaffold a tests/ directory
  - `mcp-test run`      run the pytest suite against an MCP server
  - `mcp-test demo`     run the bundled demo server + example tests (zero setup)
  - `mcp-test snapshot` snapshot helpers
  - `mcp-test coverage` print a coverage report for an MCP server
  - `mcp-test validate` validate tool schemas
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import click

__version__ = "0.2.3"


EXAMPLE_TEST = '''\
"""Example MCP server test — generated by mcp-test init."""

from mcp_test import MCPTestClient, assert_tool_ok


def test_list_tools(mcp_client):
    """Verify the server exposes at least one tool."""
    tools = mcp_client.list_tools()
    assert len(tools) > 0, "Server should expose at least one tool"


def test_tool_has_schema(mcp_client):
    """Verify every tool has a name and input schema."""
    tools = mcp_client.list_tools()
    for tool in tools:
        assert tool.name, "Tool must have a name"
        assert tool.input_schema, f"Tool {tool.name!r} must have an input schema"
'''


CONFTEST = '''\
"""pytest configuration for MCP server tests.

The mcp_client fixture is provided automatically by the pytest-mcp-plugin pytest plugin.
Pass --mcp-command on the command line, or set [tool.mcp-test] command in your
project's pyproject.toml.
"""
'''


DEMO_TEST = '''\
"""Demo tests for the bundled mcp_test._demo_server."""

from mcp_test import assert_tool_ok, assert_tool_error, assert_tool_text_equals


def test_lists_tools(mcp_client):
    tools = mcp_client.list_tools()
    names = {t.name for t in tools}
    assert {"echo", "add", "uppercase", "fail"}.issubset(names)


def test_echo(mcp_client):
    result = mcp_client.call_tool("echo", message="hello world")
    assert_tool_ok(result)
    assert_tool_text_equals(result, "hello world")


def test_add(mcp_client):
    result = mcp_client.call_tool("add", a=2, b=3)
    assert_tool_ok(result)
    assert_tool_text_equals(result, "5")


def test_uppercase(mcp_client):
    result = mcp_client.call_tool("uppercase", text="abc")
    assert_tool_text_equals(result, "ABC")


def test_fail_returns_error(mcp_client):
    result = mcp_client.call_tool("fail")
    assert_tool_error(result)
'''


@click.group()
@click.version_option(version=__version__, prog_name="mcp-test")
def main() -> None:
    """pytest for MCP servers."""


@main.command()
@click.option("--dir", "test_dir", default="tests", help="Test directory name (default: tests)")
def init(test_dir: str) -> None:
    """Scaffold a tests/ directory with example MCP tests."""
    test_path = Path(test_dir)

    if test_path.exists() and any(test_path.iterdir()):
        click.echo(f"⚠️  Directory '{test_dir}' already exists and is not empty.")
        if not click.confirm("Overwrite?"):
            raise SystemExit(0)

    test_path.mkdir(parents=True, exist_ok=True)

    test_file = test_path / "test_server.py"
    test_file.write_text(EXAMPLE_TEST)
    click.echo(f"✅ Created {test_file}")

    conftest_file = test_path / "conftest.py"
    conftest_file.write_text(CONFTEST)
    click.echo(f"✅ Created {conftest_file}")

    click.echo()
    click.echo("Run your tests with:")
    click.echo(f'  pytest {test_dir} --mcp-command "python your_server.py"')


@main.command()
@click.option(
    "--command",
    "-c",
    default=None,
    help="MCP server command (auto-discovered from pyproject.toml if not set)",
)
@click.option("--timeout", "-t", default=None, type=float, help="Request timeout (seconds)")
@click.option(
    "--timeout-method",
    "timeout_methods",
    multiple=True,
    metavar="METHOD=SECONDS",
    help="Per-method timeout override passed through to pytest",
)
@click.option("--smart-timeouts", is_flag=True, help="Enable built-in method-family timeouts")
@click.option("--trace", default=None, help="Write MCP wire trace JSONL to this path")
@click.option("--verbose", "-v", is_flag=True, help="Verbose output")
@click.option("--watch", "-w", is_flag=True, help="Re-run tests on file changes")
@click.argument("pytest_args", nargs=-1, type=click.UNPROCESSED)
def run(
    command: str | None,
    timeout: float | None,
    timeout_methods: tuple[str, ...],
    smart_timeouts: bool,
    trace: str | None,
    verbose: bool,
    watch: bool,
    pytest_args: tuple,
) -> None:
    """Run pytest against an MCP server."""
    from .runner import discover_command, discover_timeout, _run_watch_mode

    if command is None:
        command = discover_command()
        if command is None:
            click.echo(
                "❌ No --command provided and no [tool.mcp-test] command in pyproject.toml"
            )
            raise SystemExit(1)
        click.echo(f"🔍 Auto-discovered command: {command}")

    if timeout is None:
        timeout = discover_timeout()

    args = [
        sys.executable,
        "-m",
        "pytest",
        f"--mcp-command={command}",
        f"--mcp-timeout={timeout}",
    ]
    for timeout_method in timeout_methods:
        args.append(f"--mcp-timeout-method={timeout_method}")
    if smart_timeouts:
        args.append("--mcp-smart-timeouts")
    if trace:
        args.append(f"--mcp-trace={trace}")
    if verbose:
        args.append("-v")
    args.extend(pytest_args)

    if watch:
        raise SystemExit(_run_watch_mode(args))

    result = subprocess.run(args, cwd=os.getcwd())
    raise SystemExit(result.returncode)


@main.command()
@click.option(
    "--keep",
    is_flag=True,
    help="Keep the generated demo directory after running (default: clean up)",
)
@click.option("--verbose", "-v", is_flag=True, help="Verbose pytest output")
def demo(keep: bool, verbose: bool) -> None:
    """Run the bundled demo server + example tests in 5 seconds.

    No setup required. Spawns python -m mcp_test._demo_server, runs a small
    pytest suite against it, and prints the result.
    """
    server_cmd = f"{sys.executable} -m mcp_test._demo_server"
    workdir = Path(tempfile.mkdtemp(prefix="mcptest-demo-"))
    test_file = workdir / "test_demo.py"
    test_file.write_text(DEMO_TEST)

    click.echo("🚀 mcp-test demo")
    click.echo(f"   server  : {server_cmd}")
    click.echo(f"   workdir : {workdir}")
    click.echo()

    args = [
        sys.executable,
        "-m",
        "pytest",
        str(test_file),
        f"--mcp-command={server_cmd}",
        "--mcp-timeout=10",
    ]
    if verbose:
        args.append("-v")
    else:
        args.append("--tb=short")

    try:
        result = subprocess.run(args)
    finally:
        if not keep:
            shutil.rmtree(workdir, ignore_errors=True)
        else:
            click.echo()
            click.echo(f"📂 Demo files kept at: {workdir}")

    if result.returncode == 0:
        click.echo()
        click.echo("✅ Demo passed. Now write tests for your own MCP server:")
        click.echo("   mcp-test init")
    raise SystemExit(result.returncode)


@main.command("snapshot")
@click.option("--update", is_flag=True, help="Update all saved snapshots")
@click.option("--command", "-c", required=True, help="MCP server command")
@click.argument("pytest_args", nargs=-1, type=click.UNPROCESSED)
def snapshot_cmd(update: bool, command: str, pytest_args: tuple) -> None:
    """Run snapshot tests, optionally updating saved snapshots."""
    args = [
        sys.executable,
        "-m",
        "pytest",
        f"--mcp-command={command}",
    ]
    if update:
        args.append("--snapshot-update")
    args.extend(pytest_args)

    result = subprocess.run(args, cwd=os.getcwd())
    raise SystemExit(result.returncode)


@main.command()
@click.option("--command", "-c", required=True, help="MCP server command")
@click.option("--timeout", "-t", default=10.0, type=float, help="Request timeout (seconds)")
def coverage(command: str, timeout: float) -> None:
    """Print a coverage report for an MCP server's tools, prompts and resources."""
    from .client import make_client
    from .coverage import CoverageTracker, print_coverage_report

    click.echo(f"Connecting to MCP server: {command}")
    click.echo()

    with make_client(command, timeout=timeout) as client:
        tools = client.list_tools()
        prompts = client.list_prompts()
        resources = client.list_resources()

        tracker = CoverageTracker()
        tracker.register_schemas(tools, prompts, resources)

        for name in client.called_tools:
            tracker.record_call("tools", name)

        report = tracker.report()
        print_coverage_report(report)

        click.echo()
        click.echo("To improve coverage, write tests for untested tools.")
        click.echo('Run: pytest --mcp-command "' + command + '" -v')


@main.command("validate")
@click.option("--command", "-c", required=True, help="MCP server command")
@click.option("--timeout", "-t", default=10.0, type=float, help="Request timeout (seconds)")
def validate_cmd(command: str, timeout: float) -> None:
    """Validate that all tool input schemas are well-formed JSON Schema."""
    from .client import make_client
    from .schema_validator import validate_schemas

    click.echo(f"Validating schemas for: {command}")
    click.echo()

    with make_client(command, timeout=timeout) as client:
        tools = client.list_tools()
        errors = validate_schemas(tools)

        if not errors:
            click.echo("✅ All tool schemas are valid!")
            return

        has_errors = False
        for err in errors:
            icon = "❌" if err.severity == "error" else "⚠️ "
            click.echo(f"  {icon} [{err.tool_name}] {err.message}")
            if err.severity == "error":
                has_errors = True

        click.echo()
        if has_errors:
            click.echo("❌ Schema validation failed.")
            raise SystemExit(1)
        else:
            click.echo("⚠️  Schema validation passed with warnings.")


@main.command()
@click.option("--url", required=True, help="HTTP MCP endpoint URL")
@click.option("--offline", is_flag=True, help="Use the bundled offline smoke scenarios")
@click.option("--timeout", "-t", default=300.0, type=float, help="Runner timeout in seconds")
@click.option("--json-output", is_flag=True, help="Print machine-readable JSON")
@click.option("--pytest-items", is_flag=True, help="Re-emit scenarios as pytest test items")
@click.argument("extra_args", nargs=-1, type=click.UNPROCESSED)
def conformance(
    url: str,
    offline: bool,
    timeout: float,
    json_output: bool,
    pytest_items: bool,
    extra_args: tuple[str, ...],
) -> None:
    """Run Anthropic's MCP conformance suite from the mcp-test CLI."""
    import json

    from .compliance import score_conformance
    from .conformance import (
        npx_available,
        run_report_as_pytest,
        run_offline_smoke_conformance,
        run_upstream_conformance,
    )

    if offline:
        report = run_offline_smoke_conformance(url, timeout=min(timeout, 30.0))
    else:
        if not npx_available():
            click.echo("❌ npx is not available; rerun with --offline for bundled smoke scenarios.")
            raise SystemExit(2)
        report = run_upstream_conformance(url, timeout=timeout, extra_args=extra_args)

    if json_output:
        click.echo(json.dumps(report.to_json(), indent=2, sort_keys=True))
    else:
        source = "offline smoke" if report.source == "offline" else "upstream"
        click.echo(f"MCP conformance ({source}): {report.passed}/{report.total} passing ({report.percentage}%)")
        for scenario in report.scenarios:
            icon = "✅" if scenario.passed else "❌"
            suffix = f" - {scenario.message}" if scenario.message and not scenario.passed else ""
            click.echo(f"  {icon} {scenario.name}{suffix}")
        click.echo(score_conformance(report).badge_text())

    if pytest_items:
        raise SystemExit(run_report_as_pytest(report))
    raise SystemExit(0 if report.failed == 0 else 1)


@main.command()
@click.option("--command", "-c", required=True, help="MCP server command")
@click.option("--duration", default=10.0, type=float, help="Benchmark duration in seconds")
@click.option("--concurrency", default=4, type=int, help="Concurrent clients")
@click.option("--timeout", "-t", default=10.0, type=float, help="Request timeout in seconds")
@click.option("--baseline", default=None, help="Compare against a previous JSON baseline")
@click.option("--output", default=None, help="Write benchmark JSON to this file")
def bench(
    command: str,
    duration: float,
    concurrency: int,
    timeout: float,
    baseline: str | None,
    output: str | None,
) -> None:
    """Run a lightweight regression benchmark against an MCP server."""
    import json
    from pathlib import Path

    from .bench import compare_to_baseline, run_bench

    result = run_bench(
        command,
        duration_s=duration,
        concurrency=concurrency,
        timeout=timeout,
    )
    data = result.to_json()
    click.echo(json.dumps(data, indent=2, sort_keys=True))
    if output:
        Path(output).write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")

    failures = list(result.failures)
    if baseline:
        failures.extend(compare_to_baseline(result, baseline))
    for failure in failures:
        click.echo(f"❌ {failure}")
    raise SystemExit(1 if failures else 0)


if __name__ == "__main__":
    main()
