
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import click


EXAMPLE_TEST = '''\
"""Example MCP server test — generated by mcp-test init."""

from mcp_test import MCPTestClient


def test_list_tools(mcp_client):
    """Verify the server exposes at least one tool."""
    tools = mcp_client.list_tools()
    assert len(tools) > 0, "Server should expose at least one tool"


def test_tool_has_schema(mcp_client):
    """Verify every tool has a name and input schema."""
    tools = mcp_client.list_tools()
    for tool in tools:
        assert tool.name, "Tool must have a name"
        assert tool.input_schema, f"Tool {tool.name!r} must have an input schema"
"""pytest configuration for MCP server tests."""
'''


@click.group()
@click.version_option(version="0.1.0", prog_name="mcp-test")
def main():


@main.command()
@click.option("--dir", "test_dir", default="tests", help="Test directory name (default: tests)")
def init(test_dir: str):
    test_path = Path(test_dir)

    if test_path.exists() and any(test_path.iterdir()):
        click.echo(f"⚠️  Directory '{test_dir}' already exists and is not empty.")
        if not click.confirm("Overwrite?"):
            raise SystemExit(0)

    test_path.mkdir(parents=True, exist_ok=True)

    test_file = test_path / "test_server.py"
    test_file.write_text(EXAMPLE_TEST)
    click.echo(f"✅ Created {test_file}")

    conftest_file = test_path / "conftest.py"
    conftest_file.write_text(CONFTEST)
    click.echo(f"✅ Created {conftest_file}")

    click.echo()
    click.echo("Run your tests with:")
    click.echo(f'  pytest {test_dir} --mcp-command "python your_server.py"')


@main.command()
@click.option("--command", "-c", default=None, help="MCP server command (auto-discovered from pyproject.toml if not set)")
@click.option("--timeout", "-t", default=None, type=float, help="Request timeout (seconds)")
@click.option("--verbose", "-v", is_flag=True, help="Verbose output")
@click.option("--watch", "-w", is_flag=True, help="Re-run tests on file changes")
@click.argument("pytest_args", nargs=-1, type=click.UNPROCESSED)
def run(command: str | None, timeout: float | None, verbose: bool, watch: bool, pytest_args: tuple):
    from .runner import discover_command, discover_timeout, _run_watch_mode

    # Auto-discover from pyproject.toml if not provided
    if command is None:
        command = discover_command()
        if command is None:
            click.echo("❌ No --command provided and no [tool.mcp-test] command in pyproject.toml")
            raise SystemExit(1)
        click.echo(f"🔍 Auto-discovered command: {command}")

    if timeout is None:
        timeout = discover_timeout()

    args = [
        sys.executable, "-m", "pytest",
        f"--mcp-command={command}",
        f"--mcp-timeout={timeout}",
    ]
    if verbose:
        args.append("-v")
    args.extend(pytest_args)

    if watch:
        raise SystemExit(_run_watch_mode(args))

    result = subprocess.run(args, cwd=os.getcwd())
    raise SystemExit(result.returncode)


@main.command("snapshot")
@click.option("--update", is_flag=True, help="Update all saved snapshots")
@click.option("--command", "-c", required=True, help="MCP server command")
@click.argument("pytest_args", nargs=-1, type=click.UNPROCESSED)
def snapshot_cmd(update: bool, command: str, pytest_args: tuple):
    args = [
        sys.executable, "-m", "pytest",
        f"--mcp-command={command}",
    ]
    if update:
        args.append("--snapshot-update")
    args.extend(pytest_args)

    result = subprocess.run(args, cwd=os.getcwd())
    raise SystemExit(result.returncode)


@main.command()
@click.option("--command", "-c", required=True, help="MCP server command")
@click.option("--timeout", "-t", default=10.0, type=float, help="Request timeout (seconds)")
def coverage(command: str, timeout: float):
    from .client import make_client
    from .coverage import CoverageTracker, print_coverage_report

    click.echo(f"Connecting to MCP server: {command}")
    click.echo()

    with make_client(command, timeout=timeout) as client:
        tools = client.list_tools()
        prompts = client.list_prompts()
        resources = client.list_resources()

        tracker = CoverageTracker()
        tracker.register_schemas(tools, prompts, resources)

        # Record any tools already called
        for name in client.called_tools:
            tracker.record_call("tools", name)

        report = tracker.report()
        print_coverage_report(report)

        click.echo()
        click.echo("To improve coverage, write tests for untested tools.")
        click.echo('Run: pytest --mcp-command "' + command + '" -v')


@main.command("validate")
@click.option("--command", "-c", required=True, help="MCP server command")
@click.option("--timeout", "-t", default=10.0, type=float, help="Request timeout (seconds)")
def validate_cmd(command: str, timeout: float):
    from .client import make_client
    from .schema_validator import validate_schemas

    click.echo(f"Validating schemas for: {command}")
    click.echo()

    with make_client(command, timeout=timeout) as client:
        tools = client.list_tools()
        errors = validate_schemas(tools)

        if not errors:
            click.echo("✅ All tool schemas are valid!")
            return

        has_errors = False
        for err in errors:
            icon = "❌" if err.severity == "error" else "⚠️ "
            click.echo(f"  {icon} [{err.tool_name}] {err.message}")
            if err.severity == "error":
                has_errors = True

        click.echo()
        if has_errors:
            click.echo("❌ Schema validation failed.")
            raise SystemExit(1)
        else:
            click.echo("⚠️  Schema validation passed with warnings.")


if __name__ == "__main__":
    main()
